# Dockerfile
# Usar una imagen base de Python ligera
FROM python:3.9-slim-buster

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo de requisitos e instalar las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación
COPY . .

# Crear el directorio para los archivos subidos (si no existe)
RUN mkdir -p /app/uploaded_files

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 8000

# Comando para ejecutar la aplicación usando Uvicorn
# Usar gunicorn para producción con múltiples workers
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]