SECRET_KEY = os.getenv("JWT_SECRET_KEY", "super-secret-key-that-should-be-random-and-strong")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token") # Endpoint para obtener el token
